# Generated by Django 4.0.4 on 2022-05-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=50)),
                ('SafetyMail_Status', models.CharField(max_length=50)),
                ('format_valid', models.CharField(max_length=50)),
                ('mx_found', models.CharField(max_length=50)),
                ('smtp_check', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=50)),
                ('is_valid', models.CharField(max_length=50)),
                ('messef', models.CharField(max_length=50)),
            ],
        ),
    ]
